### ISSUE TITLE
Update frequency

### ISSUE THREAD

**Issue by icepick3000** [ShaneSutro/Vestaboard#23]
Hi,
Just a question here… not so much an issue but a question from a potential vestaboard user. 
Is it true you can only send out an update to your vestaboard once every 60 seconds?

**Comment by ShaneSutro** [comment]
Hi @icepick3000! Sorry for the slow response here - my understanding is that, yes, that’s the case! I’ll add that I am speaking just from my own knowledge and I am not a representative of Vestaboard, but I believe that one update per minute is what’s covered in the warranty, and so it can’t be overridden.
I think it’s enforced on an API level.
